### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [JuliaStats/Rmath-julia#39]
```gmake[1]: gcc: Command not found```

You should only use $(CC) during build.

**Comment by nalimilan** [comment]
Care to make a patch? It should be much easier for you since you can test it directly.

**Comment by yurivict** [comment]
Julia is new for me, I'm not sure how to test a local patch. It seems to download everything based on the central repositories direct from github.

**Comment by yurivict** [comment]
You should just remove any assignments to CC, like ```CC=gcc```. ```CC``` in makefiles is supposed to be supplied by the caller, and if it isn't correct - this isn't your problem. There should be no such variable as ```USE_GCC```, etc.

**Comment by nalimilan** [comment]
Yes, you should download this repository directly (instead of installing the Julia package), and see what you need to change to build it. Sorry, but only a FreeBSD user can do that.

I don't think we can rely on `CC`, because it might not be set: we need a reasonable default. FWIW, openlibm sets `USECLANG=1` on FreeBSD:
https://github.com/JuliaLang/openlibm/blob/b7b3b4bc31aa4ae42b2562e6adb151e92aa3a82a/Make.inc#L32-L35

**Comment by yurivict** [comment]
> what you need to change to build it

Remove CC=gcc. Makefiles aren't supposed to set this broadly. If some systems are only known to work with gcc, you can set this *only* for this system.

**Comment by ararslan** [comment]
I use FreeBSD, I can submit a PR for this. I've been using Rmath on FreeBSD without issue though, I guess because I have GCC installed from ports, so I never noticed that it wasn't using the default compiler.

I agree that we could use a reasonable default here, as we do with both openlibm and Julia. OpenBLAS does that as well. Though I thought the `$(CC)` automatic variable was _always_ present and set to `cc`. I could very well be wrong, and the [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html) doesn't really clear up whether the variable is always set. I believe a common pattern is `CC ?= sensible default`.

**Comment by simonbyrne** [comment]
I made a start on this in #22, but never got around to merging. Let me clean it up a bit.

**Comment by ViralBShah** [comment]
I believe we now have binaries for FreeBSD through BinaryBuilder.
